baseurl = "https://vijayanant.github.io/"
languageCode = "en-us"
title = "fossick"
theme = "hyde-hyde"

## Hugo Built-in Features
disqusShortname = "fossickio"
googleAnalytics = "UA-58152749-1"
# enableRobotsTXT = true



## Site Settings
[params]
    author = "Vijay Anant"
    title = "title goes here"
    description = "blog by Vijay Anant"
    #authorimage = "/author.png"
    highlightjs = true
    highlightjsstyle = "zenburn"
    postNavigation = false
    relatedPosts = true
    #copyright = "All Rights Reserved"

## Social Accounts
[params.social]
    email = "vijay.hassan@gmail.com"
    github = "vijayanant"
    linkedin = "vijayanant"
    twitter = "vijayanant"
    #instagram = "<username>"
    #xing = "<username>"
    #facebook = "<username>"
    #stackoverflow = "<username>"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
#[[menu.main]]
    #name = "Portfolio"
    #identifier = "portfolio"
    #weight = 200
    #url = "/portfolio/"
#[[menu.main]]
    #name = "About"
    #identifier = "about"
    #weight = 300
    #url = "/about/"

# https://gohugo.io/content-management/related
[related]
    # Only include matches with rank >= threshold. This is a normalized rank
    # between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related
    # pages.
    includeNewer = true
    # Will lower case keywords in both queries and in the indexes.
    toLower = false
[[related.indices]]
    name = "keywords"
    weight = 150
[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"
