baseurl = "https://www.vijayanant.com"
languageCode = "en-us"
theme = "hyde-hyde-vj"

## Hugo Built-in Features
#disqusShortname = "fossickio"
googleAnalytics = "UA-58152749-1"
enableRobotsTXT = false

#highlightjs = true
#highlightjsstyle = "default"
#highlightjsstyle = "github"
#highlightjsstyle = "zenburn"


# Built-in highlighting
# https://gohugo.io/content-management/syntax-highlighting
#pygmentsCodeFences = true
#pygmentsStyle = "github"
#pygmentsStyle = "friendly"
#pygmentsStyle = "monokai"
#pygmentsStyle = "default"
#pygmentsUseClasses = true     # this overrides 'PygmentsStyle'
#http://pygments.org
#pygmentsUseClassic = true     # falling back to Pygments instead of Chroma

[permalinks]
  posts = "/:section/:slug/"
  kn    = "/:section/:slug/"

## Site Settings
[params]
    title = "fossick"
    author = "Vijay Anant"
    description = "Vijay Anant"
    authorimage = "/author.png"
    googlefonts = "//fonts.googleapis.com/css?family=Muli"
    dateformat = "02 Jan 2006"
    #highlightjs = true
    #highlightjsstyle = "default"
    #highlightjsstyle = "github"
    #highlightjsstyle = "zenburn"
    postNavigation = false
    relatedPosts = true
    #copyright = "All Rights Reserved"

## Social Accounts
[params.social]
    email = "vijay.hassan@gmail.com"
    github = "vijayanant"
    linkedin = "vijayanant"
    twitter = "vijayanant"
    keybase = "vijayanant"
    #instagram = "<username>"
    #xing = "<username>"
    #facebook = "<username>"
    #stackoverflow = "<username>"

[params.meta]
    description = "blog by Vijay Anant :: technology, thoughts, opinions, and rants"
    keywords = "thoughts, programming, technology"
## Main Menu
[[menu.main]]
    name = "Archieve"
    weight = 1
    identifier = "archive"
    url = "/posts/"
[[menu.main]]
    name = "Resume"
    weight = 2
    identifier = "cv"
    url = "/resume.pdf"
[[menu.main]]
    name = "ವಿಜಯಾ೦ತರ೦ಗ"
    identifier = "kn"
    weight = 3
    url = "/kn/"
#[[menu.main]]
    #name = "Portfolio"
    #identifier = "portfolio"
    #weight = 200
    #url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4
    url = "/about/"

# https://gohugo.io/content-management/related
[related]
    # Only include matches with rank >= threshold. This is a normalized rank
    # between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related
    # pages.
    includeNewer = true
    # Will lower case keywords in both queries and in the indexes.
    toLower = false
[[related.indices]]
    name = "keywords"
    weight = 150
[[related.indices]]
    name  = "author"
    toLower = true
    weight = 30
[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name  = "date"
    weight = 10
    pattern = "2006"
